apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingresso-api
  labels:
    app: ingresso-api
spec:
  selector:
    matchLabels:
      app: ingresso-api
  replicas: 
  template:
    metadata:
      labels:
        app: ingresso-api
    spec:
      containers:
        - name: ingresso-api
          image: ingresso/ingresso-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 400m
              memory: 4000M
            limits:
              cpu: 500m
              memory: 4500M
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingresso-api-autoscaler
  namespace: default
  labels:
    label: ingresso-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingresso-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
       type: Utilization
       averageUtilization: 90
  - type: Resource
    resource: 
      name: memory
      target:
       type: Utilization
       averageUtilization: 90